<?php

/**
 * Each new term in the Fibonacci sequence is generated by adding the previous two terms. By starting with 1 and 2,
 * the first 10 terms will be:
 *
 * 1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
 *
 * By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the
 * even-valued terms.
 */

class FibonacciSequence
{
    private $previousTerm = 0;
    private $currentTerm = 1;

    public function next(): int
    {
        $nextTerm = $this->previousTerm + $this->currentTerm;
        $this->previousTerm = $this->currentTerm;
        $this->currentTerm = $nextTerm;

        return $nextTerm;
    }
}

function findSumOfEvenFibonacciTermsBelow(int $limit): int
{
    $sum = 0;
    $fibonacciSequence = new FibonacciSequence();

    for ($term = 1; $term < $limit; $term = $fibonacciSequence->next()) {
        if (isEven($term)) {
            $sum += $term;
        }
    }

    return $sum;
}

function isEven(int $integer): bool
{
    return $integer % 2 == 0;
}

echo findSumOfEvenFibonacciTermsBelow(40000000);
